export const AUTH_START = 'AUTH_START'

export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const SIGNUP_FAILED = 'SIGNUP_FAILED'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'

export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const CHANGE_USER_ROLE_START = 'CHANGE_USER_ROLE_START'
export const CHANGE_USER_ROLE_SUCCESS = 'CHANGE_USER_ROLE_SUCCESS'
export const CHANGE_USER_ROLE_FAILED = 'CHANGE_USER_ROLE_START'

export const FETCH_BUS_START = 'FETCH_BUS_START'
export const FETCH_BUS_FAILED = 'FETCH_BUS_FAILED'
export const FETCH_BUS_SUCCESS = 'FETCH_BUS_SUCCESS'

export const BOOKING_START = 'BOOKING_START'
export const BOOKING_FAILED = 'BOOKING_FAILED'
export const BOOKING_SUCCESS = 'BOOKING_SUCCESS'

export const FETCH_ALL_CITY_START = 'FETCH_ALL_CITY_START'
export const FETCH_ALL_CITY_FAILED = 'FETCH_ALL_CITY_FAILED'
export const FETCH_ALL_CITY_SUCCESS = 'FETCH_ALL_CITY_SUCCESS'

export const FETCH_CITY_SUGGESTION_START = 'FETCH_CITY_SUGGESTION_START'
export const FETCH_CITY_SUGGESTION_FAILED = 'FETCH_CITY_SUGGESTION_FAILED'
export const FETCH_CITY_SUGGESTION_SUCCESS = 'FETCH_CITY_SUGGESTION_SUCCESS'

export const FETCH_MY_BOOKINGLIST_START = 'FETCH_MY_BOOKINGLIST_START'
export const FETCH_MY_BOOKINGLIST_FAILED = 'FETCH_MY_BOOKINGLIST_FAILED'
export const FETCH_MY_BOOKINGLIST_SUCCESS = 'FETCH_MY_BOOKINGLIST_SUCCESS'

export const FETCH_ADMIN_BOOKINGLIST_START = 'FETCH_ADMIN_BOOKINGLIST_START'
export const FETCH_ADMIN_BOOKINGLIST_FAILED = 'FETCH_ADMIN_BOOKINGLIST_FAILED'
export const FETCH_ADMIN_BOOKINGLIST_SUCCESS = 'FETCH_ADMIN_BOOKINGLIST_SUCCESS'
